#include "ili9488.h"

void writeLcdCommandData(uint16_t reg, uint16_t value){
  *(uint16_t *) (LCD_REG) = reg; 
  *(uint16_t *) (LCD_DATA) = value; 
}

void writeLcdData(uint16_t data){
  *(uint16_t *) (LCD_DATA) = data;
}

void lcdInitt(void){
  
  RCC->AHBENR |= RCC_AHBENR_FSMCEN;
  
  GPIOD->CRL |= GPIO_CRL_MODE3;
  GPIOD->CRL &= ~(GPIO_CRL_CNF3);
  
  GPIOD->CRL |= (GPIO_CRL_MODE0 | GPIO_CRL_MODE1 | GPIO_CRL_MODE4 | GPIO_CRL_MODE5 | GPIO_CRL_MODE7);
  GPIOD->CRL &= ~(GPIO_CRL_CNF0 | GPIO_CRL_CNF1 | GPIO_CRL_CNF4 | GPIO_CRL_CNF5 | GPIO_CRL_CNF7);
  GPIOD->CRL |= (GPIO_CRL_CNF0_1 | GPIO_CRL_CNF1_1 | GPIO_CRL_CNF4_1 | GPIO_CRL_CNF5_1 | GPIO_CRL_CNF7_1);
  
  GPIOD->CRH |= (GPIO_CRH_MODE8 | GPIO_CRH_MODE9 | GPIO_CRH_MODE10 | GPIO_CRH_MODE11 | GPIO_CRH_MODE14 | GPIO_CRH_MODE15);
  GPIOD->CRH &= ~(GPIO_CRH_CNF8 | GPIO_CRH_CNF9 | GPIO_CRH_CNF10 | GPIO_CRH_CNF11 | GPIO_CRH_CNF14 | GPIO_CRH_CNF15);
  GPIOD->CRH |= (GPIO_CRH_CNF8_1 | GPIO_CRH_CNF9_1 | GPIO_CRH_CNF10_1 | GPIO_CRH_CNF11_1 | GPIO_CRH_CNF14_1 | GPIO_CRH_CNF15_1);
  
  GPIOE->CRL |= GPIO_CRL_MODE7;
  GPIOE->CRL &= ~(GPIO_CRL_CNF7);
  GPIOE->CRL |= GPIO_CRL_CNF7_1;
  
  GPIOE->CRH |= (GPIO_CRH_MODE8 | GPIO_CRH_MODE9 | GPIO_CRH_MODE10 | GPIO_CRH_MODE11 | GPIO_CRH_MODE12 | GPIO_CRH_MODE13 | GPIO_CRH_MODE14 | GPIO_CRH_MODE15);
  GPIOE->CRH &= ~(GPIO_CRH_CNF8 | GPIO_CRH_CNF9 | GPIO_CRH_CNF10 | GPIO_CRH_CNF11 | GPIO_CRH_CNF12 | GPIO_CRH_CNF13 | GPIO_CRH_CNF14 | GPIO_CRH_CNF15);
  GPIOE->CRH |= (GPIO_CRH_CNF8_1 | GPIO_CRH_CNF9_1 | GPIO_CRH_CNF10_1 | GPIO_CRH_CNF11_1 | GPIO_CRH_CNF12_1 | GPIO_CRH_CNF13_1 | GPIO_CRH_CNF14_1 | GPIO_CRH_CNF15_1);
  
  
  
  
  
  
}

void brighetLcdInit(void){
  
  GPIOA->CRH |= GPIO_CRH_MODE15;
  GPIOA->CRH &= ~(GPIO_CRH_CNF15);
  GPIOA->CRH |= GPIO_CRH_CNF15_1;
  
  RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
  TIM2->PSC = 0x0FFF;
  TIM2->ARR = 0xFF;
  TIM2->CCR1 = 0x01;  // Brighet LCD
  TIM2->CCER |= TIM_CCER_CC1E;
  TIM2->CCMR1 |= TIM_CCMR1_OC1M_2;
  TIM2->CCMR1 |= TIM_CCMR1_OC1M_1;
  TIM2->CCMR1 |= TIM_CCMR1_OC1PE;
  TIM2->CR1 &= ~TIM_CR1_DIR;
  TIM2->CR1 &= ~TIM_CR1_CMS;
  TIM2->CR1 |= TIM_CR1_ARPE;
  TIM2->CR1 |= TIM_CR1_CEN; // Timer Brighet
}
