#include "setting.h"

void setting(void){
  
  SysTick_Config(SystemCoreClock / 1000); //1ms
  
  RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;
  RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;
  RCC->APB2ENR |= RCC_APB2ENR_IOPBEN;
  RCC->APB2ENR |= RCC_APB2ENR_IOPCEN;
  RCC->APB2ENR |= RCC_APB2ENR_IOPDEN;
  RCC->APB2ENR |= RCC_APB2ENR_IOPEEN;
  RCC->APB2ENR |= RCC_APB2ENR_IOPFEN;
  RCC->APB2ENR |= RCC_APB2ENR_IOPGEN;
  
  rtcInit();
  
  GPIOA->CRH &= ~(GPIO_CRH_CNF15);
  GPIOA->CRH |= GPIO_CRH_CNF15_1;
//  GPIOA->CRH &= ~(GPIO_CRH_MODE15);
  GPIOA->CRH |= GPIO_CRH_MODE15; // LCD Brighet
  
  RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
  TIM2->PSC = 0x3FFF;
  TIM2->ARR = 0x0F;
  TIM2->CCR1 = 0x00;  // Brighet LCD
  TIM2->CCER |= TIM_CCER_CC1E;
  TIM2->BDTR |= TIM_BDTR_MOE | TIM_BDTR_BKP;
  TIM2->CCMR1 = TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1PE;
  TIM2->CR1 &= ~TIM_CR1_DIR;
  TIM2->CR1 &= ~TIM_CR1_CMS;
  TIM2->CR1 |= TIM_CR1_ARPE;
  TIM2->CR1 |= TIM_CR1_CEN; // Timer Brighet



}






